language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - "pip install -r requirements.txt"

# command to run tests, e.g. python setup.py test
script: "bash run-tests.sh"

notifications:
  email:
    - rother.magdalena@gmail.com
    - krother@academis.eu
    - ppiatkowski@genesilico.pl

branches:
  except:
    - py3
    - workingtests
